[package]
name = "osx-dock-dodger-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
wry = { version = "0.40", features = ["drag-drop"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
plist = "1"
tao = "0.32"
